import { defineConfig } from "vite";
import viteReact from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsConfigPaths from "vite-tsconfig-paths";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";

// Plain, explicit Vite config (previously generated by @lovable.dev/vite-tanstack-config).
// tanstackStart's nitro target controls what platform this builds for.
// "vercel" builds this as Vercel-compatible serverless functions.
// If you deploy elsewhere later, change target below (e.g. "node-server" for a
// plain Node host, "netlify" for Netlify, "cloudflare-module" for Cloudflare Workers).
export default defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    tsConfigPaths({
      projects: ["./tsconfig.json"],
    }),
    tailwindcss(),
    tanstackStart({
      target: "vercel",
      server: {
        entry: "server",
      },
    }),
    viteReact(),
  ],
});
