/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganisationsIndexRouteImport } from './routes/organisations.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as OrganisationsSlugRouteImport } from './routes/organisations.$slug'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSetPasswordRouteImport } from './routes/_authenticated/set-password'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as CommunityPostIdRouteImport } from './routes/community.post.$id'
import { Route as AuthenticatedDashboardUserRouteImport } from './routes/_authenticated/dashboard/user'
import { Route as AuthenticatedDashboardOrgRouteImport } from './routes/_authenticated/dashboard/org'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin/verifications'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminOrganisationsRouteImport } from './routes/_authenticated/admin/organisations'
import { Route as AuthenticatedAdminOpportunitiesRouteImport } from './routes/_authenticated/admin/opportunities'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin/ingestion'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated/admin/community'
import { Route as AuthenticatedAdminAllowlistRouteImport } from './routes/_authenticated/admin/allowlist'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin/accounts'
import { Route as ApiPublicHooksReengageRouteImport } from './routes/api/public/hooks/reengage'
import { Route as ApiPublicHooksIngestOpportunitiesRouteImport } from './routes/api/public/hooks/ingest-opportunities'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsIndexRoute = OrganisationsIndexRouteImport.update({
  id: '/organisations/',
  path: '/organisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationsSlugRoute = OrganisationsSlugRouteImport.update({
  id: '/organisations/$slug',
  path: '/organisations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetPasswordRoute =
  AuthenticatedSetPasswordRouteImport.update({
    id: '/set-password',
    path: '/set-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/community/post/$id',
  path: '/community/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardUserRoute =
  AuthenticatedDashboardUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrgRoute =
  AuthenticatedDashboardOrgRouteImport.update({
    id: '/org',
    path: '/org',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminOrganisationsRoute =
  AuthenticatedAdminOrganisationsRouteImport.update({
    id: '/organisations',
    path: '/organisations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOpportunitiesRoute =
  AuthenticatedAdminOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAllowlistRoute =
  AuthenticatedAdminAllowlistRouteImport.update({
    id: '/allowlist',
    path: '/allowlist',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicHooksReengageRoute = ApiPublicHooksReengageRouteImport.update({
  id: '/api/public/hooks/reengage',
  path: '/api/public/hooks/reengage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestOpportunitiesRoute =
  ApiPublicHooksIngestOpportunitiesRouteImport.update({
    id: '/api/public/hooks/ingest-opportunities',
    path: '/api/public/hooks/ingest-opportunities',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/set-password': typeof AuthenticatedSetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organisations/$slug': typeof OrganisationsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/org': typeof AuthenticatedDashboardOrgRoute
  '/dashboard/user': typeof AuthenticatedDashboardUserRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/ingest-opportunities': typeof ApiPublicHooksIngestOpportunitiesRoute
  '/api/public/hooks/reengage': typeof ApiPublicHooksReengageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/set-password': typeof AuthenticatedSetPasswordRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organisations/$slug': typeof OrganisationsSlugRoute
  '/community': typeof CommunityIndexRoute
  '/organisations': typeof OrganisationsIndexRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/org': typeof AuthenticatedDashboardOrgRoute
  '/dashboard/user': typeof AuthenticatedDashboardUserRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/ingest-opportunities': typeof ApiPublicHooksIngestOpportunitiesRoute
  '/api/public/hooks/reengage': typeof ApiPublicHooksReengageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/set-password': typeof AuthenticatedSetPasswordRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/organisations/$slug': typeof OrganisationsSlugRoute
  '/community/': typeof CommunityIndexRoute
  '/organisations/': typeof OrganisationsIndexRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/opportunities': typeof AuthenticatedAdminOpportunitiesRoute
  '/_authenticated/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/org': typeof AuthenticatedDashboardOrgRoute
  '/_authenticated/dashboard/user': typeof AuthenticatedDashboardUserRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/ingest-opportunities': typeof ApiPublicHooksIngestOpportunitiesRoute
  '/api/public/hooks/reengage': typeof ApiPublicHooksReengageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/alerts'
    | '/profile'
    | '/saved'
    | '/set-password'
    | '/settings'
    | '/community/$slug'
    | '/opportunities/$id'
    | '/organisations/$slug'
    | '/community/'
    | '/organisations/'
    | '/admin/accounts'
    | '/admin/allowlist'
    | '/admin/community'
    | '/admin/ingestion'
    | '/admin/opportunities'
    | '/admin/organisations'
    | '/admin/users'
    | '/admin/verifications'
    | '/dashboard/admin'
    | '/dashboard/org'
    | '/dashboard/user'
    | '/community/post/$id'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/hooks/ingest-opportunities'
    | '/api/public/hooks/reengage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/alerts'
    | '/profile'
    | '/saved'
    | '/set-password'
    | '/settings'
    | '/community/$slug'
    | '/opportunities/$id'
    | '/organisations/$slug'
    | '/community'
    | '/organisations'
    | '/admin/accounts'
    | '/admin/allowlist'
    | '/admin/community'
    | '/admin/ingestion'
    | '/admin/opportunities'
    | '/admin/organisations'
    | '/admin/users'
    | '/admin/verifications'
    | '/dashboard/admin'
    | '/dashboard/org'
    | '/dashboard/user'
    | '/community/post/$id'
    | '/admin'
    | '/dashboard'
    | '/api/public/hooks/ingest-opportunities'
    | '/api/public/hooks/reengage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/feed'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/alerts'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/_authenticated/set-password'
    | '/_authenticated/settings'
    | '/community/$slug'
    | '/opportunities/$id'
    | '/organisations/$slug'
    | '/community/'
    | '/organisations/'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/allowlist'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/opportunities'
    | '/_authenticated/admin/organisations'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/org'
    | '/_authenticated/dashboard/user'
    | '/community/post/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/api/public/hooks/ingest-opportunities'
    | '/api/public/hooks/reengage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  OrganisationsSlugRoute: typeof OrganisationsSlugRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  OrganisationsIndexRoute: typeof OrganisationsIndexRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  ApiPublicHooksIngestOpportunitiesRoute: typeof ApiPublicHooksIngestOpportunitiesRoute
  ApiPublicHooksReengageRoute: typeof ApiPublicHooksReengageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/': {
      id: '/organisations/'
      path: '/organisations'
      fullPath: '/organisations/'
      preLoaderRoute: typeof OrganisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisations/$slug': {
      id: '/organisations/$slug'
      path: '/organisations/$slug'
      fullPath: '/organisations/$slug'
      preLoaderRoute: typeof OrganisationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/set-password': {
      id: '/_authenticated/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthenticatedSetPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/community/post/$id': {
      id: '/community/post/$id'
      path: '/community/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/user': {
      id: '/_authenticated/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AuthenticatedDashboardUserRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/org': {
      id: '/_authenticated/dashboard/org'
      path: '/org'
      fullPath: '/dashboard/org'
      preLoaderRoute: typeof AuthenticatedDashboardOrgRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/organisations': {
      id: '/_authenticated/admin/organisations'
      path: '/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AuthenticatedAdminOrganisationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/opportunities': {
      id: '/_authenticated/admin/opportunities'
      path: '/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AuthenticatedAdminOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/allowlist': {
      id: '/_authenticated/admin/allowlist'
      path: '/allowlist'
      fullPath: '/admin/allowlist'
      preLoaderRoute: typeof AuthenticatedAdminAllowlistRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/reengage': {
      id: '/api/public/hooks/reengage'
      path: '/api/public/hooks/reengage'
      fullPath: '/api/public/hooks/reengage'
      preLoaderRoute: typeof ApiPublicHooksReengageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-opportunities': {
      id: '/api/public/hooks/ingest-opportunities'
      path: '/api/public/hooks/ingest-opportunities'
      fullPath: '/api/public/hooks/ingest-opportunities'
      preLoaderRoute: typeof ApiPublicHooksIngestOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminAllowlistRoute: typeof AuthenticatedAdminAllowlistRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminOpportunitiesRoute: typeof AuthenticatedAdminOpportunitiesRoute
  AuthenticatedAdminOrganisationsRoute: typeof AuthenticatedAdminOrganisationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
    AuthenticatedAdminAllowlistRoute: AuthenticatedAdminAllowlistRoute,
    AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
    AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
    AuthenticatedAdminOpportunitiesRoute: AuthenticatedAdminOpportunitiesRoute,
    AuthenticatedAdminOrganisationsRoute: AuthenticatedAdminOrganisationsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardOrgRoute: typeof AuthenticatedDashboardOrgRoute
  AuthenticatedDashboardUserRoute: typeof AuthenticatedDashboardUserRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardOrgRoute: AuthenticatedDashboardOrgRoute,
    AuthenticatedDashboardUserRoute: AuthenticatedDashboardUserRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSetPasswordRoute: typeof AuthenticatedSetPasswordRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSetPasswordRoute: AuthenticatedSetPasswordRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  OrganisationsSlugRoute: OrganisationsSlugRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  OrganisationsIndexRoute: OrganisationsIndexRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
  ApiPublicHooksIngestOpportunitiesRoute:
    ApiPublicHooksIngestOpportunitiesRoute,
  ApiPublicHooksReengageRoute: ApiPublicHooksReengageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
